ALTER TABLE market_snapshots
    ADD COLUMN IF NOT EXISTS no_bid NUMERIC(10, 4),
    ADD COLUMN IF NOT EXISTS no_ask NUMERIC(10, 4),
    ADD COLUMN IF NOT EXISTS no_bid_size INTEGER,
    ADD COLUMN IF NOT EXISTS no_ask_size INTEGER;
